#define POLAR_STAT_LEARNING_CANCEL_FAILED		-3
#define POLAR_STAT_MSG_ID_NOT_RECD				-2
#define POLAR_STAT_RECORDING_COUNT_ERROR		-1

#define POLAR_STAT_FINAL_RESPONSE 				1
#define POLAR_STAT_FIRST_RESPONSE				2
#define POLAR_STAT_LEARNING_STARTED				3
#define POLAR_STAT_ALREADY_LEARNING				5
#define POLAR_STAT_LEARNING_CANCEL_SUCCESSFUL	7

#define POLAR_STAT_NODE_NOT_FOUND				-5001
#define POLAR_STAT_NODE_SEND_FAILED				-5002
#define POLAR_STAT_NODE_REPLY_ERROR				-1000
#define POLAR_STAT_PARAMS_MISSING				-3000
#define POLAR_STAT_PARAMS_INCORRECT				-3001